name: Laravel CI/CD (Self-Hosted)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # ===============================
  # 1️⃣ BUILD
  # ===============================
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Instalar dependências
        run: |
          composer install --no-interaction --no-progress --prefer-dist
          cp .env.example .env || true
          php artisan key:generate || true
          php artisan config:cache || true
          php artisan route:cache || true
          php artisan view:cache || true

  # ===============================
  # 2️⃣ QUALIDADE
  # ===============================
  quality:
    runs-on: self-hosted
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Testes e análise
        run: |
          vendor/bin/phpunit --colors=always || true
          vendor/bin/phpstan analyse --no-progress || true
          vendor/bin/phpcs --standard=PSR12 app/ || true

  # ===============================
  # 3️⃣ DEPLOY
  # ===============================
  deploy:
    runs-on: self-hosted
    needs: quality

    steps:
      - uses: actions/checkout@v4
      - name: Deploy local
        run: |
          echo "🚀 Iniciando deploy..."
          rm -rf /home/fiocruzlab/todo-app/*
          cp -r ./* /home/fiocruzlab/todo-app/
          cd /home/fiocruzlab/todo-app
          composer install --no-interaction --no-progress --prefer-dist --optimize-autoloader
          php artisan config:cache || true
          php artisan route:cache || true
          php artisan view:cache || true
          echo "✅ Deploy finalizado com sucesso!"
