name: Deploy Laravel App

on:
  push:
    branches:
      - main   # ou altere para a branch principal do seu projeto

jobs:
  deploy:
    name: Deploy Laravel App (Self-Hosted)
    runs-on: self-hosted

    steps:
      # 1️⃣ Faz checkout do código fonte
      - name: Checkout código
        uses: actions/checkout@v4

      # 2️⃣ Mostra o diretório atual (debug opcional)
      - name: Mostrar diretório atual
        run: pwd

      # 3️⃣ Cria o diretório do deploy e ajusta permissões
      - name: Criar diretório do deploy
        run: |
          echo "🔧 Criando diretório de destino..."
          sudo mkdir -p /srv/apps/todo-app/public
          sudo chown -R git-runner:git-runner /srv/apps
          echo "✅ Diretório pronto em /srv/apps/todo-app/public"

      # 4️⃣ Instala dependências PHP (Composer)
      - name: Instalar dependências PHP
        run: |
          echo "📦 Instalando dependências do Laravel..."
          composer install --no-interaction --no-progress --prefer-dist
          echo "✅ Dependências instaladas com sucesso!"

      # 5️⃣ Copia arquivos para o servidor com rsync
      - name: Fazer deploy com rsync
        run: |
          echo "🚀 Iniciando deploy..."
          rsync -avz --delete ./ /srv/apps/todo-app/public
          echo "✅ Deploy concluído!"

      # 6️⃣ Configura ambiente Laravel (caso exista o .env)
      - name: Configurar ambiente Laravel
        run: |
          echo "⚙️ Configurando ambiente Laravel..."
          if [ -f /srv/apps/todo-app/public/.env ]; then
            echo "✅ Arquivo .env encontrado"
          else
            echo "⚠️ Nenhum .env encontrado — certifique-se de criá-lo!"
          fi

      # 7️⃣ Otimiza a aplicação Laravel (cache)
      - name: Otimizar Laravel
        run: |
          cd /srv/apps/todo-app/public
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          echo "✨ Laravel otimizado com sucesso!"

      # 8️⃣ Reinicia os serviços web (Nginx e PHP-FPM)
      - name: Reiniciar serviços
        run: |
          echo "🔁 Reiniciando Nginx e PHP-FPM..."
          sudo systemctl restart nginx
          sudo systemctl restart php-fpm
          echo "✅ Serviços reiniciados com sucesso!"
