name: Laravel CI/CD

on:
  push:
    branches:
      - main

jobs:
  quality:
    name: Stage de Qualidade
    runs-on: self-hosted

    steps:
      - name: Checkout do código
        run: |
          if [ ! -d ".git" ]; then
            git clone https://github.com/${GITHUB_REPOSITORY}.git .
          fi
          git fetch origin main
          git reset --hard origin/main

      - name: Verificar PHP instalado
        run: php -v

      - name: Verificar Composer instalado
        run: composer -V

      - name: Instalar dependências
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Copiar arquivo .env de exemplo
        run: cp .env.example .env || true

      - name: Gerar chave da aplicação
        run: php artisan key:generate

      - name: Rodar testes (PHPUnit)
        run: vendor/bin/phpunit --testdox

      - name: Rodar análise estática (PHPStan)
        run: vendor/bin/phpstan analyse --memory-limit=1G

      - name: Rodar CodeSniffer (PSR-12)
        run: vendor/bin/phpcs

  deploy:
    name: Stage de Deploy
    runs-on: self-hosted
    needs: quality

    steps:
      - name: Atualizar código da branch main
        run: |
          cd /var/www/html/laravel-app
          sudo git fetch origin main
          sudo git reset --hard origin/main

      - name: Instalar dependências de produção
        run: |
          cd /var/www/html/laravel-app
          composer install --no-dev --optimize-autoloader

      - name: Otimizar Laravel (cache de config, rotas e views)
        run: |
          cd /var/www/html/laravel-app
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      - name: Ajustar permissões
        run: |
          sudo chown -R nginx:nginx /var/www/html/laravel-app
          sudo chmod -R 775 /var/www/html/laravel-app/storage /var/www/html/laravel-app/bootstrap/cache

      - name: Reiniciar serviços
        run: |
          sudo systemctl restart php-fpm
          sudo systemctl restart nginx
